### PR TITLE
Update SendVenue.cs

### PR DESCRIPTION
**Pull request by Lunat1q**

### CODE REVIEW

**Review by justdmitry — APPROVED** [review]
Wow, sad typo. Thank you

**Comment by justdmitry** [comment]
[v3.9.0-beta2](https://www.nuget.org/packages/NetTelegramBotApi/3.9.0-beta2) uploaded to NuGet

**Comment by Lunat1q** [comment]
Also, when you do ".ToString()" should be ".ToString(CultureInfo.InvariantCulture)"

**Comment by justdmitry** [comment]
Yep. Updated everywhere. 

BTW, I added all v2.2 (October 2016) changes - now we should have everything except 'Updating messages' and 'Inline mode'

**Pull request merged**
